2025-04-25 16:22:02,697 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:22:09,362 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:22:10,809 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:22:11,396 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:22:11,975 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
